#!/bin/sh
#
#      Jonathan Perkin <jonathan@perkin.org.uk> wrote this file.
#
# You can freely distribute/modify it (and are encouraged to do so),
# and you are welcome to buy me a beer if we ever meet and you think
# this stuff is worth it.  Improvements and cleanups always welcome.
#
# Wrapper script to open/save a PGP encrypted file.
#


PLAINFILE="$HOME/.pw"
ENCRYPTFILE="${PLAINFILE}.gpg"
PGPKEYID="jonathan@perkin.org.uk"

: ${EDITOR=vi}

# Just in case we forget to fix up permissions, ensure a tight umask.
umask 077

if [ -f ${PLAINFILE} ]; then
    echo "${PLAINFILE} already exists, perhaps from an existing"
    echo "session.  Please check and remove."
    exit 1
fi

if [ -f ${ENCRYPTFILE} ]; then
    gpg --output ${PLAINFILE} --decrypt ${ENCRYPTFILE}
    if [ $? -ne 0 ]; then
        rm -f ${PLAINFILE}
        exit 1
    fi
else
    # Create secure-ish plain file for decrypted data.
    > ${PLAINFILE}
fi
chmod 0600 ${PLAINFILE}

# Create timestamp file to check if the decrypted file has been updated,
# and launch editor session on decrypted file.
> ${PLAINFILE}.touched
$EDITOR ${PLAINFILE}

# Check for any changes, if none then cleanup and exit.  "-nt" isn't supported
# by Solaris /bin/sh but I'm not really bothered about that anymore, and can't
# be bothered to run find(1) -newer instead.
if [ ! ${PLAINFILE} -nt ${PLAINFILE}.touched ]; then

    # Write some random data to ${PLAINFILE} to scrub it, then delete it.
    fsize=$(du -sk ${PLAINFILE} | awk '{print $1}')
    dd if=/dev/urandom of=${PLAINFILE} bs=1k count=${fsize} conv=notrunc,fsync 2>/dev/null
    rm -f ${PLAINFILE} ${PLAINFILE}.touched
    exit
fi

# Save previous copy of encrypted file.
if [ -f ${ENCRYPTFILE} ]; then
    rm -f ${ENCRYPTFILE}.prev
    mv ${ENCRYPTFILE} ${ENCRYPTFILE}.prev
fi

# Encrypt file.
gpg --output ${ENCRYPTFILE} --encrypt --armor -r ${PGPKEYID} ${PLAINFILE}

# Remove unencrypted file after scrubbing it.
fsize=$(du -sk ${PLAINFILE} | awk '{print $1}')
dd if=/dev/urandom of=${PLAINFILE} bs=1k count=${fsize} conv=notrunc,fsync 2>/dev/null
rm -f ${PLAINFILE} ${PLAINFILE}.touched

# Ensure sane file permissions on encrypted files.
chmod 0400 ${ENCRYPTFILE}*
