#!/bin/sh
#
#      Jonathan Perkin <jonathan@perkin.org.uk> wrote this file.
#
# You can freely distribute/modify it (and are encouraged to do so),
# and you are welcome to buy me a beer if we ever meet and you think
# this stuff is worth it.  Improvements and cleanups always welcome.
#
# Wrapper script around VirtualBox to delete VMs quickly.
#


if [ $# -ne 1 ]; then
    echo "usage: rmvboxvm <name>"
    exit 2
fi

vmname=$1; shift

VBoxManage unregistervm "${vmname}" --delete
