#!/bin/sh
#
#      Jonathan Perkin <jonathan@perkin.org.uk> wrote this file.
#
# You can freely distribute/modify it (and are encouraged to do so),
# and you are welcome to buy me a beer if we ever meet and you think
# this stuff is worth it.  Improvements and cleanups always welcome.
#
# Simple wrapper script around ffmpeg to strip MPEG2-TS to MPEG.
#
# Creates files approximately 66% the size of the original as all the
# subtitles and extra audio tracks are removed, and improves the
# compatibility (in my case this is done for playback via WiiMC).
#


#
# Nothing special, take .ts input file and create .mkv version
#
if [ $# -lt 1 -o $# -gt 2 ]; then
    echo "usage: ts2mkv input.ts <output.mkv>"
    exit 2
fi

infile=$1; shift
if [ -n "$1" ]; then
    outfile=$1; shift
else
    outfile=`basename ${infile} | sed -e 's/.ts$/.mkv/'`
fi

ffmpeg -i ${infile} -acodec copy -vcodec copy -map 0:0 -map 0:1 ${outfile}
